# Generated by Django 2.2.5 on 2019-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
